### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [nickbild/vectron_vga_plus#1]
Hello!

I found this repository from https://hackaday.com/2021/12/14/a-slim-7400-logic-vga-board-for-all-your-retro-needs/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and images in any purpose?
It would be great to see any popular open source license.

**Comment by nickbild** [comment]
Done.

**Comment by vazhnov** [comment]
MIT — amazing!
@nickbild, thank you very much!
